In [29]:
import pandas as pd

In [30]:
df = pd.read_csv("/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/evaluation_dataset.csv")

In [31]:
df.head()

,id,text
0,/Users/midhunln/Documents/rag20march_with_eval...,Page 1 of 132 \n \n \nMASTER CIRCULAR \n \nSEB...
1,/Users/midhunln/Documents/rag20march_with_eval...,Securities and Exchange Board of India (Issue ...
2,/Users/midhunln/Documents/rag20march_with_eval...,Page 2 of 132 \n \n4. With the issuance of thi...
3,/Users/midhunln/Documents/rag20march_with_eval...,"suffered thereunder, any right, privilege, obl..."
4,/Users/midhunln/Documents/rag20march_with_eval...,regulations and bidding portal. \n7. All liste...

In [32]:
df["id"][0]

'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_0_0'

In [33]:
df.info

<bound method DataFrame.info of                                                      id  \
0     /Users/midhunln/Documents/rag20march_with_eval...
1     /Users/midhunln/Documents/rag20march_with_eval...
2     /Users/midhunln/Documents/rag20march_with_eval...
3     /Users/midhunln/Documents/rag20march_with_eval...
4     /Users/midhunln/Documents/rag20march_with_eval...
...                                                 ...
1103  /Users/midhunln/Documents/rag20march_with_eval...
1104  /Users/midhunln/Documents/rag20march_with_eval...
1105  /Users/midhunln/Documents/rag20march_with_eval...
1106  /Users/midhunln/Documents/rag20march_with_eval...
1107  /Users/midhunln/Documents/rag20march_with_eval...

                                                   text
0     Page 1 of 132 \n \n \nMASTER CIRCULAR \n \nSEB...
1     Securities and Exchange Board of India (Issue ...
2     Page 2 of 132 \n \n4. With the issuance of thi...
3     suffered thereunder, any right, privilege, obl...
4     regulations and bidding portal. \n7. All liste...
...                                                 ...
1103  Page 26 of 28 \n \nAnnexure -6 \n \nReport by ...
1104  quarter. \n \n5 Total no of exemptions given t...
1105  Page 27 of 28 \n \nAnnexure 7 \nList of rescin...
1106  regarding violations of SEBI (PIT) \nRegulatio...
1107  Page 28 of 28 \n \nS. \nNo. \nDate Number Subj...

[1108 rows x 2 columns]>

In [34]:
df_sampled = df.sample(frac = 0.1)

In [35]:
df_sampled.head()

,id,text
458,/Users/midhunln/Documents/rag20march_with_eval...,paragraph 9 below. \n \n7.2. If a listed entit...
808,/Users/midhunln/Documents/rag20march_with_eval...,(b) From which marginalized /vulnerable groups...
358,/Users/midhunln/Documents/rag20march_with_eval...,6. The notice being sent to the shareholders s...
858,/Users/midhunln/Documents/rag20march_with_eval...,"Act, 1961 (43 of 1961). \nReference: http://eb..."
577,/Users/midhunln/Documents/rag20march_with_eval...,"results for the period from ………… to …………, atta..."

In [36]:
!pip install langchain-ollama

Requirement already satisfied: langchain-ollama in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (1.0.1)
Requirement already satisfied: langchain-core<2.0.0,>=1.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-ollama) (1.2.20)
Requirement already satisfied: ollama<1.0.0,>=0.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-ollama) (0.6.1)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.22)
Requirement already satisfied: packaging>=23.2.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (24.2)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.12.5)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.14.1)
Requirement already satisfied: httpx>=0.27 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from ollama<1.0.0,>=0.6.0->langchain-ollama) (0.28.1)
Requirement already satisfied: anyio in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (4.12.1)
Requirement already satisfied: certifi in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (1.0.9)
Requirement already satisfied: idna in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.27->ollama<1.0.0,>=0.6.0->langchain-ollama) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.32.5)
Requirement already satisfied: xxhash>=3.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.7.4->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=1.0.0->langchain-ollama) (2.6.3)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [37]:
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage

chat = ChatOllama(model = "llama3")

In [38]:
from langchain_ollama import ChatOllama
from langchain_core.messages import HumanMessage

chat = ChatOllama(model="llama3")

def llm_call(text):
    prompt = f"""
You are a query generator. Based on the text below, generate a concise search query
that a user would likely use to find this information. The output must only have the query and nothing else.
It is very important that the output is only the query and nothing else.

Text:
{text}
"""
    response = chat.invoke([HumanMessage(content=prompt)])
    return response.content.strip()


# Apply row-wise correctly
df_sampled["query"] = df_sampled["text"].apply(llm_call)

In [39]:
df_sampled["query"].iloc[2]

'"Proposed RPT disclosure requirements"'

In [40]:
df_sampled.to_csv("eval_with_query.csv", index = False)

In [41]:
df_sampled.head()

,id,text,query
458,/Users/midhunln/Documents/rag20march_with_eval...,paragraph 9 below. \n \n7.2. If a listed entit...,"""lodr regulations non compliance"""
808,/Users/midhunln/Documents/rag20march_with_eval...,(b) From which marginalized /vulnerable groups...,"""marginalized groups procurement percentage"""
358,/Users/midhunln/Documents/rag20march_with_eval...,6. The notice being sent to the shareholders s...,"""Proposed RPT disclosure requirements"""
858,/Users/midhunln/Documents/rag20march_with_eval...,"Act, 1961 (43 of 1961). \nReference: http://eb...","""Income Tax Act 1961 salary definition"""
577,/Users/midhunln/Documents/rag20march_with_eval...,"results for the period from ………… to …………, atta...","""company financial results"""

# Construct the qrels dataset for rankx

In [42]:
qrels = {}

for _, row in df_sampled.iterrows():
    query = row["query"]
    doc_id = row["id"]

    if query not in qrels:
        qrels[query] = {}

    qrels[query][doc_id] = 1  # relevance score

In [43]:
qrels

{'"lodr regulations non compliance"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_52_58': 1},
 '"marginalized groups procurement percentage"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_174_8': 1},
 '"Proposed RPT disclosure requirements"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_18_158': 1},
 '"Income Tax Act 1961 salary definition"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_191_58': 1},
 '"company financial results"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_99_177': 1},
 '"blocked funds unblock delayed"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_124_84': 1},
 '"responsible business conduct sustainability issues"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_182_30': 1},
 '"health and safety practices"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_157_173': 1},
 '"number of complaints by employees on human rights issues"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_160_181': 1},
 '"SEBI Regulation 33 Listing Obligations Disclosure"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_98_175': 1},
 '"Companies Act 2013 definitions"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_180_23': 1},
 '"Audio visual presentation of public issue offer documents"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_12_31': 1},
 '"compliance report"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_137_128': 1},
 '"offer document disclosures"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_50_138': 1},
 '"consolidated financial results"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_123_90': 1,
  '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_122_82': 1},
 '"Page 93"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_92_18': 1},
 '"LODR regulations timeline for disclosing events"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_228_160': 1},
 '"waste management practices e-waste bio-medical waste"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_198_80': 1},
 '"NIL report funds raised submission deadline"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_20_166': 1},
 '"GHG emission intensity"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_167_193': 1},
 '"minimum compensation for investor failure"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_14_36': 1},
 '"Application form for IPO bidding"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_85_4': 1},
 '"SEBI promoter group open market sale regulation"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_34_10': 1},
 '"audit qualification"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_130_115': 1},
 '"consolidated financial statements subsidiaries audit standards"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_105_4': 1},
 '"Open Offer submission guidelines"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_75_183': 1},
 '"conflict of interest governance"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_185_38': 1},
 '"parental leave return to work rate retention rate"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_188_47': 1},
 '"stakeholder grievance mechanism"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_181_28': 1},
 '"Secretarial compliance report SEBI Act"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_136_125': 1},
 '"corporate policy influence responsible transparency"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_201_87': 1},
 '"unaffected price rumor confirmation"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_238_191': 1},
 '"child labour laws in India"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_193_64': 1},
 '"When did an event/information occur for disclosure under Regulation 30 LODR Regulations?"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_234_178': 1},
 '"stock exchange website shareholding pattern disclosure"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_10_131': 1},
 '"ASBA guidelines for SCSBs"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_97_33': 1},
 '"ICDR Regulations 2018 dissemination requirements"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_19_49': 1},
 '"Key Performance Indicators KPIs"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_43_126': 1},
 '"Annexure"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_3_11': 1},
 '"interim financial statements not reviewed"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_104_0': 1},
 '"types of renewable energy"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_194_67': 1},
 '"National Guidelines for Responsible Business Conduct"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_178_15': 1},
 '"NGRBC principles management processes"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_145_146': 1},
 '"shareholding pattern regulation 2021"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_8_125': 1},
 '"ASBA complaints compensation"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_15_39': 1},
 '"ipo mandate details"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_120_76': 1},
 '"Unified Payments Interface UPI"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_28_82': 1},
 '"stock exchange file format"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_97_34': 1},
 '"page 92"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_91_17': 1},
 '"WAP variation July 27 2023"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_237_187': 1},
 '"number of employees rehabilitated after high consequence work-related injury"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_157_174': 1},
 '"SEBI industry standards rumors verification"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_26_185': 1},
 '"quarterly financial results Parent SEBI Regulation 33"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_117_58': 1},
 '"SEBI Regulation 33 unaudited financial results"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_113_42': 1},
 '"going concern basis of accounting audit report"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_107_13': 1},
 '"SEBI SAST Regulations open offer ISD"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_74_180': 1},
 '"market rumour adjustment VWAP"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_237_188': 1},
 '"listing requirements India"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_57_153': 1},
 '"SEBI insider trading report"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular on Surveillance of Securities Market.pdf_17_86': 1},
 '"ISD preferential securities issue"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_59_156': 1},
 '"ASBA facility complaints"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_123_82': 1},
 '"financial reporting of group associates jointly controlled entities AS 25 Ind AS 34"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_121_80': 1},
 '"ICDR Regulations draft offer document submission"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_51_141': 1},
 '"board meeting minutes recording and dissemination procedures"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_246_8': 1},
 '"stock exchange fines non-compliance listed entities"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_51_53': 1},
 '"Corporate action reissue"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master Circular for Issue of Capital and Disclosure Requirements.pdf_37_110': 1},
 '"consolidated unaudited financial results subsidiaries"': {'/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_103_195': 1},

# Start retriever

In [44]:
!pip install langchain-pinecone

Requirement already satisfied: langchain-pinecone in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (0.2.13)
Requirement already satisfied: langchain-core<2.0.0,>=0.3.34 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (1.2.20)
Requirement already satisfied: pinecone<8.0.0,>=6.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (7.3.0)
Requirement already satisfied: numpy!=2.0.2,>=1.26.4 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (2.3.1)
Requirement already satisfied: langchain-openai>=0.3.11 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (1.1.11)
Requirement already satisfied: httpx>=0.28.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (0.28.1)
Requirement already satisfied: simsimd>=5.9.11 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (6.5.16)
Requirement already satisfied: pydantic>=2.11.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-pinecone) (2.12.5)
Requirement already satisfied: anyio in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (4.12.1)
Requirement already satisfied: certifi in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (2026.2.25)
Requirement already satisfied: httpcore==1.* in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (1.0.9)
Requirement already satisfied: idna in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpx>=0.28.0->langchain-pinecone) (3.11)
Requirement already satisfied: h11>=0.16 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from httpcore==1.*->httpx>=0.28.0->langchain-pinecone) (0.16.0)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (1.33)
Requirement already satisfied: langsmith<1.0.0,>=0.3.45 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (0.7.22)
Requirement already satisfied: packaging>=23.2.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (24.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (6.0.3)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (9.1.4)
Requirement already satisfied: typing-extensions<5.0.0,>=4.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (4.15.0)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (0.14.1)
Requirement already satisfied: openai<3.0.0,>=2.26.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-openai>=0.3.11->langchain-pinecone) (2.29.0)
Requirement already satisfied: tiktoken<1.0.0,>=0.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langchain-openai>=0.3.11->langchain-pinecone) (0.12.0)
Requirement already satisfied: pinecone-plugin-assistant<2.0.0,>=1.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.8.0)
Requirement already satisfied: pinecone-plugin-interface<0.0.8,>=0.0.7 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (0.0.7)
Requirement already satisfied: python-dateutil>=2.5.3 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.9.0.post0)
Requirement already satisfied: urllib3>=1.26.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.6.3)
Requirement already satisfied: aiohttp>=3.9.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (3.13.3)
Requirement already satisfied: aiohttp-retry<3.0.0,>=2.9.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.9.1)
Requirement already satisfied: annotated-types>=0.6.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic>=2.11.1->langchain-pinecone) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic>=2.11.1->langchain-pinecone) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from pydantic>=2.11.1->langchain-pinecone) (0.4.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (0.4.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from aiohttp>=3.9.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.23.0)
Requirement already satisfied: jsonpointer>=1.9 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.0.0)
Requirement already satisfied: orjson>=3.9.14 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.11.7)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (1.0.0)
Requirement already satisfied: requests>=2.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (2.32.5)
Requirement already satisfied: xxhash>=3.0.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.6.0)
Requirement already satisfied: zstandard>=0.23.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (0.25.0)
Requirement already satisfied: distro<2,>=1.7.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (1.9.0)
Requirement already satisfied: jiter<1,>=0.10.0 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (0.13.0)
Requirement already satisfied: sniffio in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (1.3.1)
Requirement already satisfied: tqdm>4 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from openai<3.0.0,>=2.26.0->langchain-openai>=0.3.11->langchain-pinecone) (4.67.3)
Requirement already satisfied: six>=1.5 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from python-dateutil>=2.5.3->pinecone<8.0.0,>=6.0.0->pinecone[asyncio]<8.0.0,>=6.0.0->langchain-pinecone) (1.17.0)
Requirement already satisfied: regex>=2022.1.18 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from tiktoken<1.0.0,>=0.7.0->langchain-openai>=0.3.11->langchain-pinecone) (2026.2.28)
Requirement already satisfied: charset_normalizer<4,>=2 in /Users/midhunln/.pyenv/versions/3.12.10/lib/python3.12/site-packages (from requests>=2.0.0->langsmith<1.0.0,>=0.3.45->langchain-core<2.0.0,>=0.3.34->langchain-pinecone) (3.4.6)

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [45]:
import sys
sys.path.append('/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval')

from dotenv import load_dotenv
load_dotenv("/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/ingestion.env")

from Repositories.pinecone_repository import PineconeRepository

In [46]:
from Repositories.pinecone_repository import PineconeConfig
from src.sentence_transformer_embedding import SentenceTransformerEmbedding
from src.sparse_embedding import SentenceTransformerSparseEmbedding

In [47]:
config = PineconeConfig()

dense_embedding_strategy = SentenceTransformerEmbedding(config)

sparse_embedding_strategy = SentenceTransformerSparseEmbedding(config)

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 5765.79it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
Loading weights: 100%|██████████| 204/204 [00:00<00:00, 24407.75it/s]
The tied weights mapping and config for this model specifies to tie bert.embeddings.word_embeddings.weight to cls.predictions.decoder.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
The tied weights mapping and config for this model specifies to tie cls.predictions.bias to cls.predictions.decoder.bias, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
BertForMaskedLM LOAD REPORT from: naver/splade-cocondenser-ensembledistil
Key                          | Status     |  |
-----------------------------+------------+--+-
bert.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [48]:
import os

In [49]:
pinecone_repository = PineconeRepository(
            api_key=os.getenv("PINECONE_API_KEY"),
            environment=os.getenv("PINECONE_ENVIRONMENT", "us-east-1-aws"),
            dense_embedding_strategy=dense_embedding_strategy,
            sparse_embedding_strategy=sparse_embedding_strategy,
            pinecone_config=config
        )

In [50]:
df_sampled["relevant_docs"] = df_sampled["query"].apply(pinecone_repository.query_vector_store_for_rankx)

In [51]:
df_sampled.head()

,id,text,query,relevant_docs
458,/Users/midhunln/Documents/rag20march_with_eval...,paragraph 9 below. \n \n7.2. If a listed entit...,"""lodr regulations non compliance""",[{'id': '/Users/midhunln/Documents/rag20march_...
808,/Users/midhunln/Documents/rag20march_with_eval...,(b) From which marginalized /vulnerable groups...,"""marginalized groups procurement percentage""",[{'id': '/Users/midhunln/Documents/rag20march_...
358,/Users/midhunln/Documents/rag20march_with_eval...,6. The notice being sent to the shareholders s...,"""Proposed RPT disclosure requirements""",[{'id': '/Users/midhunln/Documents/rag20march_...
858,/Users/midhunln/Documents/rag20march_with_eval...,"Act, 1961 (43 of 1961). \nReference: http://eb...","""Income Tax Act 1961 salary definition""",[{'id': '/Users/midhunln/Documents/rag20march_...
577,/Users/midhunln/Documents/rag20march_with_eval...,"results for the period from ………… to …………, atta...","""company financial results""",[{'id': '/Users/midhunln/Documents/rag20march_...

In [52]:
df_sampled["relevant_docs"].iloc[0]

[{'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_56_72',
  'score': 24.3381386},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_47_42',
  'score': 23.9980011},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_48_46',
  'score': 23.8759499},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_81_125',
  'score': 22.7297096},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_84_133',
  'score': 22.6994438},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_52_58',
  'score': 22.6776505},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_47_43',
  'score': 22.2314262},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_0_103',
  'score': 22.226038},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_56_73',
  'score': 22.1570492},
 {'id': '/Users/midhunln/Documents/rag20march_with_eval/Ingestion_plus_Retriever_eval/Documents/Master circular for compliance with the provisions of the Securities and Exchange Board of India (Listing Obligations and Disclosure Requirements) Regulations, 2015 by listed entities.pdf_47_45',
  'score': 22.0487404}]

In [53]:
qrels_dict = {}

for i, row in df_sampled.iterrows():
    qid = str(i)
    true_doc = row["id"]   # single doc id string
    qrels_dict[qid] = {true_doc: 1}

In [54]:
run_dict = {}

for i, row in df_sampled.iterrows():
    qid = str(i)
    
    run_dict[qid] = {
        doc["id"]: float(doc["score"])
        for doc in row["relevant_docs"]
    }

In [56]:
from ranx import Qrels, Run, evaluate

qrels = Qrels(qrels_dict)
run = Run(run_dict)

metrics = [
    "mrr",
    "ndcg@10",
    "recall@5",
    "recall@10",
    "precision@5"
]

results = evaluate(qrels, run, metrics)
print(results)

{'mrr': np.float64(0.09219219219219218), 'ndcg@10': np.float64(0.10942265482505567), 'recall@5': np.float64(0.15315315315315314), 'recall@10': np.float64(0.16216216216216217), 'precision@5': np.float64(0.030630630630630633)}